version: "3.8"

services:
  HelloMicrometer:
    image: ghcr.io/jexxa-projects/jlegmedmicrometer/jlegmedmicrometer:0.latest

    networks:
      - public-digilab

    deploy:
      labels:
        # Enable traefic routing
        - traefik.enable=true
        - traefik.swarm.network=public-digilab

        # Configure routing for micrometer
        - traefik.http.routers.micrometer.tls=true
        - traefik.http.routers.micrometer.entrypoints=websecure

        - traefik.http.routers.micrometer.rule=PathPrefix(`/micrometer`)
        - traefik.http.routers.micrometer.middlewares=micrometer@swarm

        # Define the middleware micrometer
        - traefik.http.middlewares.micrometer.stripprefix.prefixes=/micrometer

        # Configure the service
        - traefik.http.services.micrometer.loadbalancer.server.port=8080 # In docker-swarm we must define the public port of the application this way

        - prometheus.scrape=true
        - prometheus.port=8080
        - prometheus.app_name=jlegmedmicrometer

networks:
  public-digilab:
    external: true